default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my-blog
  username: my-blog-user  # Updated to use the new user you created
  password: 12345        # Password for the new user
  host: localhost
  port: 5432

test:
  <<: *default
  database: blog_test
  username: my-blog-user  # Updated to use the new user you created
  password: 12345        # Password for the new user
  host: localhost
  port: 5432
